### ISSUE TITLE
Can i add simple http web server file in go folder?

### ISSUE THREAD

**Issue by lingeshwaran05** [Ayushsingh07/HELPERR#26]

**Comment by Ayushsingh07** [comment]
if its written in other lang then make a new folder if its a go file then yeah go for it.

**Comment by lingeshwaran05** [comment]
its http request file so it contains two html files also , so what can i do , can i upload it in go folder or make a separate folder inside go folder

**Comment by Ayushsingh07** [comment]
yeah totally fine ...greate work
