### ISSUE TITLE
Add sorting algorithms

### ISSUE THREAD

**Issue by divyansh-nishad** [Ayushsingh07/HELPERR#39]
Contributors are required to sort algorithms (C/C++) in this repository. The PR is merged only if the code is commented properly and all the conditions of this repo are satisfied.

**Comment by Unknown-hunk** [comment]
It will be my pleasure to work on above issue.

**Comment by divyansh-nishad** [comment]
> It will be my pleasure to work on above issue.
Then add the sorting algorithms in the C/C++ folder and remember to satisfy all conditions written in Readme file

**Comment by div8791** [comment]
I can do that.

**Comment by komalpandeyy** [comment]
I would like to work on this. Please assign this to me

**Comment by Ayushsingh07** [comment]
open for all  
just do it
