### ISSUE TITLE
Car racing game

### ISSUE THREAD

**Issue by devUT27** [Ayushsingh07/HELPERR#69]
Hello Utkarsh here. I'm a beginner web developer and new to open source
Here is a little game I created with HTML, CSS, Javascript.
Please add this game under Hacktober fest. Thank you
![game](https://user-images.githubusercontent.com/97338476/193842321-a67b3902-fba6-40eb-a166-5406ea871049.png)
![Screenshot 2022-10-04 142308](https://user-images.githubusercontent.com/97338476/193842342-c7274211-3827-43cd-a6fd-48c2ec4af145.png)

**Comment by Ayushsingh07** [comment]
u can create a pull request.
and more if u want to
